<?php

$encoding0 = Array (
    "method"=> '4kr3ofeptwgary2j',
    "boundsParamsList"=> 'n27qzc8389kgakyv',
    "id"=> '39031qie1i4aq563',
    "minLatE6"=> 'pg98bwox95ly0ouu',
    "minLngE6"=> 'eib1bkq8znpwr0g7',
    "maxLatE6"=> 'ilfap961rwdybv63',
    "maxLngE6"=> 'lpf7m1ifx0ieouzq',
    "timestampMs"=> '2ewujgywmum1yp49',
    "qk"=> 'bgxibcomzoto63sn',
    "desiredNumItems"=> 'tmb0vgxgp5grsnhp',
    "minTimestampMs"=> 'hljqffkpwlx0vtjt',
    "maxTimestampMs"=> 'sw317giy6x2xj9zm',
    "guids"=> 'pusjrhxxtyp5nois',
    "inviteeEmailAddress"=> 'cltkepgqkepfsyaq',
    "message"=> 'q0d6n7t1801bb6xu',
    "latE6"=> '5ygbhpxfnt1u9e4t',
    "lngE6"=> 'ak6twnljwwcgd7cj',
    "factionOnly"=> '0dvtbatgzcfccchh'
  );
$encoding1 = Array (
    "method"=> 'uuo2zqhhy5bw80fu',
    "boundsParamsList"=> '5rc0561uauf6x13u',
    "id"=> 'bzeizowtguoyrrtt',
    "minLatE6"=> '7qej3eqg4sefuaac',
    "minLngE6"=> 'yqegc976egk5q9vo',
    "maxLatE6"=> '2odsgh99ix9bbtsb',
    "maxLngE6"=> 'g9jess8dwa2j8pwi',
    "timestampMs"=> '604f34zcu9zna0a5',
    "qk"=> 'y853tux9h7cb6xp3',
    "desiredNumItems"=> 'sfv5i7l6ouljz8vf',
    "minTimestampMs"=> 'y3g07dbnw6sklloj',
    "maxTimestampMs"=> '3pdl28aa27xvyhke',
    "guids"=> 'xp1pl2jm5hrh3bna',
    "inviteeEmailAddress"=> '2pyrttrp3gh38mmu',
    "message"=> 'zz54435vfc57nlg9',
    "latE6"=> 'cyltxjod3jhxgj8q',
    "lngE6"=> 'h9whcgcz6kpqkz80',
    "factionOnly"=> '37okcr7gvd5yn2lj'
  );

?>